export default [
  {
    line: "good morning and welcome to a special edition of this week one on one with the commander in chief at this defining.",
    start_time: "0",
    end_time: "7",
    speaker: "Rep",
    conv_no: 0,
  },
  {
    line: "moment of the Obama presidency this is not a world we should accept this is what the distinction with a crisis.",
    start_time: "7",
    end_time: "14",
    speaker: "Prospect",
    conv_no: 1,
  },
  {
    line: "overseas new showdowns with Congress here at home we go inside the White House challenging a president trying to.",
    start_time: "14",
    end_time: "22",
    speaker: "Rep",
    conv_no: 2,
  },
  {
    line: "save his second term and stop a war one-on-one with President Obama you've done in the pen no no no George and ABC.",
    start_time: "22",
    end_time: "30",
    speaker: "Prospect",
    conv_no: 3,
  },
  {
    line: "News exclusive plus live analysis from our powerhouse Roundtable it's all right here this Sunday morning from ABC News a special this week with George.",
    start_time: "30",
    end_time: "43",
    speaker: "Prospect",
    conv_no: 4,
  },
  {
    line: "Stephanopoulos starts now it has been a perilous month for President Obama after that chemical.",
    start_time: "43",
    end_time: "52",
    speaker: "Rep",
    conv_no: 5,
  },
  {
    line: "weapons massacre in Syria he took America right to the brink of a military strike then backed away turning to Congress first and surprisingly the Russians choosing diplomacy over war and.",
    start_time: "52",
    end_time: "63",
    speaker: "Rep",
    conv_no: 6,
  },
  {
    line: "this weekend a major new development Secretary of State John Kerry and his Russian counterpart have struck a deal for Syria to surrender its chemical weapons if it works and that's a big if.",
    start_time: "63",
    end_time: "74",
    speaker: "Prospect",
    conv_no: 7,
  },
  {
    line: "right now the president may be able to claim a measure of victory for an approach that's brought him a mountain of criticism and on the eve of the deal we went inside the White House to speak.",
    start_time: "74",
    end_time: "84",
    speaker: "Prospect",
    conv_no: 8,
  },
  {
    line: "with the president he was confident convinced that America is in a better position now than when he was poised to order military action just two weeks ago.",
    start_time: "84",
    end_time: "93",
    speaker: "Rep",
    conv_no: 9,
  },
  {
    line: "we're definitely that's a better position but keep in mind that my entire goal throughout this exercise is to make sure that what happened on August 21st does not happen again that we do not see over a thousand people over 400 children.",
    start_time: "93",
    end_time: "109",
    speaker: "Rep",
    conv_no: 10,
  },
  {
    line: "subjected to poison gas something that is a violation of international law and is a violation and that won't happen occasionally well I think we have the possibility of making sure that it doesn't happen again think about where we work this event.",
    start_time: "109",
    end_time: "125",
    speaker: "Prospect",
    conv_no: 11,
  },
  {
    line: "happens and the initial response is the Syrians act as if they don't know anything about it at that point they're not even acknowledging that they've got chemical weapons the Russians are protecting the Syrians suggesting that.",
    start_time: "125",
    end_time: "140",
    speaker: "Prospect",
    conv_no: 12,
  },
  {
    line: "there's no possibility that the Assad regime might have done this and the inspectors weren't even in yet and as a consequence of the pressure that we've applied over the last couple of weeks we.",
    start_time: "140",
    end_time: "153",
    speaker: "Rep",
    conv_no: 13,
  },
  {
    line: "have serious for the first time acknowledging that it has chemical weapons agreeing to join the convention that prohibits the use of chemical weapons and the Russians their primary.",
    start_time: "153",
    end_time: "164",
    speaker: "Rep",
    conv_no: 14,
  },
  {
    line: "sponsors saying that they will push Syria to get all of their chemical weapons out the distance that we've traveled over these couple of weeks is remarkable in my position and the United States position has been consistent.",
    start_time: "164",
    end_time: "178",
    speaker: "Rep",
    conv_no: 15,
  },
  {
    line: "throughout we is that the underlying civil conflict in Syria is terrible I believe that because of Assad's actions his response to peaceful protest we've created a civil war in Syria that has led to a hundred.",
    start_time: "178",
    end_time: "197",
    speaker: "Rep",
    conv_no: 16,
  },
  {
    line: "thousand people being killed and six million people being displaced but what I've also said is that the United States can't get in the middle of somebody else's Civil War we're not going to put troops on the ground we can't enforce.",
    start_time: "197",
    end_time: "211",
    speaker: "Rep",
    conv_no: 17,
  },
  {
    line: "militarily a settlement there but instead he had to go what we can do what we can do is make sure that the worst weapons the indiscriminate weapons that don't distinguish between a soldier and an infant are not used and if we get that accomplished then we may also have a foundation to begin what has to be an.",
    start_time: "211",
    end_time: "234",
    speaker: "Prospect",
    conv_no: 18,
  },
  {
    line: "international process in which Assad sponsors primarily Iran and Russia recognized that this is terrible for the Syrian people and they are willing to.",
    start_time: "234",
    end_time: "245",
    speaker: "Prospect",
    conv_no: 19,
  },
  {
    line: "come in a serious way to arrive at some sort of political settlement that would deal with the underlying terrible conflict and president Putin's become.",
    start_time: "245",
    end_time: "253",
    speaker: "Prospect",
    conv_no: 20,
  },
  {
    line: "you're unlikely partner in this and you.",
    start_time: "253",
    end_time: "256",
    speaker: "Rep",
    conv_no: 21,
  },
  {
    line: "know even in this outfit which is sort of a lot of controversy here in the.",
    start_time: "256",
    end_time: "259",
    speaker: "Rep",
    conv_no: 22,
  },
  {
    line: "United States he said there's every reason to believe that the rebels are the ones who use the chemical weapon so does that tell you.",
    start_time: "259",
    end_time: "265",
    speaker: "Rep",
    conv_no: 23,
  },
  {
    line: "he's willing to lie to protect Assad well nobody around the world takes seriously the idea that the rebels were.",
    start_time: "265",
    end_time: "274",
    speaker: "Prospect",
    conv_no: 24,
  },
  {
    line: "the perpetrators devoting their time well I understand what I said there's nobody around the world takes seriously.",
    start_time: "274",
    end_time: "281",
    speaker: "Prospect",
    conv_no: 25,
  },
  {
    line: "the idea that the rebels perpetrated this attack now what is true is that there are radical elements in the.",
    start_time: "281",
    end_time: "289",
    speaker: "Rep",
    conv_no: 26,
  },
  {
    line: "opposition including folks who are affiliated with al Qaeda who if they got their hands on chemical weapons would have no compunction using them in Syria.",
    start_time: "289",
    end_time: "299",
    speaker: "Rep",
    conv_no: 27,
  },
  {
    line: "or outside of Syria and part of the reason why we've been so concerned about this chemical weapons issue is because we don't want those folks getting.",
    start_time: "299",
    end_time: "310",
    speaker: "Rep",
    conv_no: 28,
  },
  {
    line: "chemical weapons any more than we want Assad to have chemical weapons and so the best solution is for us to get them out of there but with.",
    start_time: "310",
    end_time: "318",
    speaker: "Rep",
    conv_no: 29,
  },
  {
    line: "respect to mr.",
    start_time: "318",
    end_time: "319",
    speaker: "Prospect",
    conv_no: 30,
  },
  {
    line: "Putin I have said consistently that where the interest of the United States and Russia converged we need to work together and I've talked.",
    start_time: "319",
    end_time: "326",
    speaker: "Prospect",
    conv_no: 31,
  },
  {
    line: "to mr.",
    start_time: "326",
    end_time: "327",
    speaker: "Rep",
    conv_no: 32,
  },
  {
    line: "Putin a year ago saying to him the United States and Russia should work together to deal with these chemical.",
    start_time: "327",
    end_time: "333",
    speaker: "Rep",
    conv_no: 33,
  },
  {
    line: "weapons stockpiles and to work to try to bring about a political transition has her same goal do you really tell that I don't think that mr.",
    start_time: "333",
    end_time: "339",
    speaker: "Prospect",
    conv_no: 34,
  },
  {
    line: "Putin has the same values that.",
    start_time: "339",
    end_time: "345",
    speaker: "Prospect",
    conv_no: 35,
  },
  {
    line: "we do and I think obviously by protecting mr.",
    start_time: "345",
    end_time: "348",
    speaker: "Rep",
    conv_no: 36,
  },
  {
    line: "Assad he has a different attitude about the Assad regime but what I've also said to him directly is that.",
    start_time: "348",
    end_time: "358",
    speaker: "Rep",
    conv_no: 37,
  },
  {
    line: "we both have an interest in preventing chaos we both have an interest in preventing terrorism the situation in Syria right now is untenable as long as.",
    start_time: "358",
    end_time: "368",
    speaker: "Prospect",
    conv_no: 38,
  },
  {
    line: "mr.",
    start_time: "368",
    end_time: "369",
    speaker: "Prospect",
    conv_no: 39,
  },
  {
    line: "Assad is in power there is going to be some sort of conflict there and that we should work together to try to find a way in which the interests of all the.",
    start_time: "369",
    end_time: "377",
    speaker: "Prospect",
    conv_no: 40,
  },
  {
    line: "parties inside of Syria the Alaa whites the Sunnis the Christians that everybody is represented and that there is a way of bringing the temperature down so that.",
    start_time: "377",
    end_time: "390",
    speaker: "Rep",
    conv_no: 41,
  },
  {
    line: "the horrible things that are happening inside the country or containing the Hammond I think there is a way for mr.",
    start_time: "390",
    end_time: "397",
    speaker: "Rep",
    conv_no: 42,
  },
  {
    line: "Putin despite me and him having a whole.",
    start_time: "397",
    end_time: "400",
    speaker: "Prospect",
    conv_no: 43,
  },
  {
    line: "lot of differences to play an important role in that and so I welcome him being involved I welcome him saying I will take responsibility for pushing my.",
    start_time: "400",
    end_time: "411",
    speaker: "Prospect",
    conv_no: 44,
  },
  {
    line: "client the Assad regime to deal with these chemical weapons because I think that if in fact not only Russia gets involved but if potentially Iran gets involved as well in recognizing that.",
    start_time: "411",
    end_time: "426",
    speaker: "Rep",
    conv_no: 45,
  },
  {
    line: "what's happening there is a train wreck that hurts not just Syrians but destabilize I shall read all the Putin's being on time and playing you well you.",
    start_time: "426",
    end_time: "436",
    speaker: "Rep",
    conv_no: 46,
  },
  {
    line: "know Ronald Reagan said trust but verify and I think that that's always been the experience of US presidents when we're interacting with four Soviet leaders and.",
    start_time: "436",
    end_time: "446",
    speaker: "Rep",
    conv_no: 47,
  },
  {
    line: "now Russian leaders mr.",
    start_time: "446",
    end_time: "448",
    speaker: "Rep",
    conv_no: 48,
  },
  {
    line: "putin and i have strong disagreements on all range of issues but i can talk to him we have worked.",
    start_time: "448",
    end_time: "456",
    speaker: "Prospect",
    conv_no: 49,
  },
  {
    line: "together on important issues the fact the matter is is that we couldn't be supplying all of our troops in Afghanistan if he weren't helping us in transporting those supplies through the.",
    start_time: "456",
    end_time: "467",
    speaker: "Prospect",
    conv_no: 50,
  },
  {
    line: "northern border northern borders of Afghanistan so there are a whole range of areas where we currently work together we've worked together on counterterrorism operations and so you.",
    start_time: "467",
    end_time: "476",
    speaker: "Rep",
    conv_no: 51,
  },
  {
    line: "know this is not the Cold War this is not a contest between the United States and Russia I mean the fact of the matter is is that if Russia wants to have some.",
    start_time: "476",
    end_time: "488",
    speaker: "Rep",
    conv_no: 52,
  },
  {
    line: "influence in Syria post-assad that doesn't hurt our interests I know that sometimes this gets framed or looked at through the lens of the US versus Russia but that's not what this is about what.",
    start_time: "488",
    end_time: "501",
    speaker: "Rep",
    conv_no: 53,
  },
  {
    line: "this is about is how do we make sure that we don't have the worst weapons in.",
    start_time: "501",
    end_time: "505",
    speaker: "Rep",
    conv_no: 54,
  },
  {
    line: "the hands either of a murderous regime or in the alternative some elements of the opposition that are as opposed to.",
    start_time: "505",
    end_time: "515",
    speaker: "Rep",
    conv_no: 55,
  },
  {
    line: "the United States as they are to Assad this weekend after intense talks the US and Russia hammered down a deal providing this framework is fully implemented it can end the threat these.",
    start_time: "515",
    end_time: "528",
    speaker: "Prospect",
    conv_no: 56,
  },
  {
    line: "weapons pose not only to the Syrian people but also to their neighbors to the region it calls for Syria to admit.",
    start_time: "528",
    end_time: "536",
    speaker: "Prospect",
    conv_no: 57,
  },
  {
    line: "international inspectors by November and to allow its chemical weapons to be destroyed starting next year but.",
    start_time: "536",
    end_time: "542",
    speaker: "Rep",
    conv_no: 58,
  },
  {
    line: "President Assad has not yet endorsed a deal and the rebels fighting his regime fear it will empower him if one year from now Assad is in the process of.",
    start_time: "542",
    end_time: "552",
    speaker: "Rep",
    conv_no: 59,
  },
  {
    line: "surrendering his chemical weapons but he strengthened his hold on power is that a victory well the chemical weapons issue is the issue I'm concerned about first.",
    start_time: "552",
    end_time: "563",
    speaker: "Rep",
    conv_no: 60,
  },
  {
    line: "and foremost simply because that speaks directly to US interests it speaks to the potential that other countries start.",
    start_time: "563",
    end_time: "573",
    speaker: "Prospect",
    conv_no: 61,
  },
  {
    line: "producing more chemical weapons that the ban on chemical weapons unravels and it becomes more accessible to terrorists which in turn could be you.",
    start_time: "573",
    end_time: "580",
    speaker: "Prospect",
    conv_no: 62,
  },
  {
    line: "against us so I have a primary concern there I also believe that the US has an interest in seeing a stable Syria in.",
    start_time: "580",
    end_time: "592",
    speaker: "Prospect",
    conv_no: 63,
  },
  {
    line: "which people aren't being slaughtered and it is hard to envision how mr.",
    start_time: "592",
    end_time: "595",
    speaker: "Rep",
    conv_no: 64,
  },
  {
    line: "Assad regains any kind of legitimacy after.",
    start_time: "595",
    end_time: "601",
    speaker: "Rep",
    conv_no: 65,
  },
  {
    line: "he's gassed or his military has gassed innocent civilians and children and so part of my argument here is that we will.",
    start_time: "601",
    end_time: "612",
    speaker: "Rep",
    conv_no: 66,
  },
  {
    line: "not intervene militarily to bring that transition about but all the countries in the region and I think the entire world and the United Nations should have.",
    start_time: "612",
    end_time: "622",
    speaker: "Rep",
    conv_no: 67,
  },
  {
    line: "an interest in trying to bring about that stability what do you think it Ron makes of all this you mentioned Iran do you think they can look at all this and.",
    start_time: "622",
    end_time: "630",
    speaker: "Rep",
    conv_no: 68,
  },
  {
    line: "say maybe all options aren't on the table you're not willing to use force no I think I think the Iranians who we communicate with in indirect ways have.",
    start_time: "630",
    end_time: "640",
    speaker: "Prospect",
    conv_no: 69,
  },
  {
    line: "you reached out personally the new president I have and and he's reached out to me we haven't spoken directly but letters.",
    start_time: "640",
    end_time: "647",
    speaker: "Prospect",
    conv_no: 70,
  },
  {
    line: "yeah and I think what the Iranians understand is that the nuclear issue is a far larger issue for us than the chemical weapons issue that the threat.",
    start_time: "647",
    end_time: "663",
    speaker: "Rep",
    conv_no: 71,
  },
  {
    line: "against Iran against Israel that nuclear Iran poses is much closer to our core interests that a nuclear arms race in the region is something that would be.",
    start_time: "663",
    end_time: "677",
    speaker: "Rep",
    conv_no: 72,
  },
  {
    line: "profoundly destabilizing and so I my suspicion is that the Iranians recognized they shouldn't draw a lesson.",
    start_time: "677",
    end_time: "685",
    speaker: "Rep",
    conv_no: 73,
  },
  {
    line: "that we hadn't struck to think we won't strike a run on the other hand what it what they should draw from this lesson is that there is the potential of.",
    start_time: "685",
    end_time: "695",
    speaker: "Prospect",
    conv_no: 74,
  },
  {
    line: "resolving these issues diplomatically there's anything they believe that I think they recognize in part because of.",
    start_time: "695",
    end_time: "704",
    speaker: "Prospect",
    conv_no: 75,
  },
  {
    line: "the extraordinary sanctions that we placed on them that the world community is united when it comes to wanting to.",
    start_time: "704",
    end_time: "711",
    speaker: "Rep",
    conv_no: 76,
  },
  {
    line: "prevent a nuclear arms race in the region and you know negotiations with the Iranians is always difficult I think this new president is not going to suddenly make.",
    start_time: "711",
    end_time: "722",
    speaker: "Rep",
    conv_no: 77,
  },
  {
    line: "it easy but my view is that if you have both a credible threat of force combined with a rigorous diplomatic effort that in fact you can you can strike a deal.",
    start_time: "722",
    end_time: "743",
    speaker: "Rep",
    conv_no: 78,
  },
  {
    line: "and I and I hold out I hold out that hope final foreign policy questions had some month a lot of armchair criticism I'm sure you're used to that I am.",
    start_time: "743",
    end_time: "752",
    speaker: "Rep",
    conv_no: 79,
  },
  {
    line: "senator corker Foreign Relations Committee said you're not comfortable as commander in chief it's like watching a person who's caged the president of.",
    start_time: "752",
    end_time: "760",
    speaker: "Prospect",
    conv_no: 80,
  },
  {
    line: "counsel Foreign Relations Richard Haass words like ad-hoc improvised unsteady come to mind this is probably the most undisciplined stretch of foreign policy.",
    start_time: "760",
    end_time: "768",
    speaker: "Prospect",
    conv_no: 81,
  },
  {
    line: "in your presidency what do you make of that well you know I I think that folks here in Washington like to grade on style and so had we rolled out something that was very smooth and disciplined and linear.",
    start_time: "768",
    end_time: "792",
    speaker: "Rep",
    conv_no: 82,
  },
  {
    line: "they would have graded it well even if it was a disastrous policy we know that because that's exactly how they graded the Iraq war until sitting in our.",
    start_time: "792",
    end_time: "803",
    speaker: "Rep",
    conv_no: 83,
  },
  {
    line: "President Bush not know what would what it says is that I'm less concerned about style points I'm much more concerned about getting the policy right and what.",
    start_time: "803",
    end_time: "816",
    speaker: "Prospect",
    conv_no: 84,
  },
  {
    line: "I've said consistently throughout is that the chemical weapons issue is a problem I want that problem dealt with and as a consequence of the steps that.",
    start_time: "816",
    end_time: "829",
    speaker: "Prospect",
    conv_no: 85,
  },
  {
    line: "we've taken over the last two weeks to three weeks we now have a situation in which Syria has acknowledged it as chemical weapons has said it's willing.",
    start_time: "829",
    end_time: "837",
    speaker: "Rep",
    conv_no: 86,
  },
  {
    line: "to join the Convention on chemical weapons and Russia its primary sponsor has said that it will pressure Syria to reach that agreement that's my goal and if that goal is achieved then it sounds to me like we did something right.",
    start_time: "837",
    end_time: "853",
    speaker: "Rep",
    conv_no: 87,
  },
  {
    line: "and we have much more from President Obama all the challenges here at home when we come back.",
    start_time: "853",
    end_time: "860",
    speaker: "Prospect",
    conv_no: 88,
  },
]